### ISSUE TITLE
torch version to run a demo code for FNet

### ISSUE THREAD

**Issue by ra312** [labmlai/annotated_deep_learning_paper_implementations#61] opened 2021-06-19 14:15 UTC
Hi guys! Thanks for the awesome work! I am excited to play with the code. Here is the gist
https://gist.github.com/ra312/f3c895aba6e8954985258de10e9be52f
At the first attempt, I am encountered  this exception

<img width="863" alt="image" src="https://user-images.githubusercontent.com/12486277/122645152-bd598100-d13a-11eb-8a6b-15824f1f8f46.png">

I believe the right version of pytorch shold help to fix this!
These are my current dependencies

<img width="463" alt="image" src="https://user-images.githubusercontent.com/12486277/122645170-d104e780-d13a-11eb-8226-b1f38fb006f6.png">

If someone can advise on torch version, it would save me time and be super cool!
Many thanks, Rauan.

**Comment by dnairns-arch** [comment] 2021-06-20 04:14
I ran into the same exact issue. I deleted the min_freq from the nlp_classification.py and then I ended up with another error.

`IndexError: index out of range in self`

Seems to be more than one issue with the FNet code...

![image](https://user-images.githubusercontent.com/74305659/122661833-74b2bf80-d15c-11eb-811e-d52ead92d0ed.png)

**Comment by vpj** [comment] 2021-06-20 12:35
Hi,

I am sorry, I don't know why you get this error.

`Vocab` accepts parameter `min_freq` - [documentation](https://pytorch.org/text/stable/vocab.html#torchtext.vocab.vocab), and you have the latest version (same as documentation). 

Can you try initializing `torchtext.vocab.Vocab(Counter(), min_freq=1)` and see if you still get this error?

**Comment by vpj** [comment] 2021-06-20 12:41
Ok, great I could reproduce the error on google colab. I'll see whats going on and get back to you.

**Comment by vpj** [comment] 2021-06-20 12:46
found it, looks like its a function `vocab` class `Vocab` used to take these parameters as input in older `torchtext` versions. Will upgrade my setup and update the code. Thanks for opening the issue.

**Comment by vpj** [comment] 2021-06-20 13:38
Looks like `torchtext=0.10` requires `torch=1.9`, can you try downgrading to `torchtext=0.9` for now (which uses `torch=1.8`)?.

I will have to test all experiments and models before moving to `torch=1.9`.

Thanks

**Comment by dnairns-arch** [comment] 2021-06-20 14:46
Downgraded the versions to torch==1.8, and torchtext==0.9. 

Re-added min_freq=1 back to nlp-classification

The FNet model is now training. 

I was getting my error due to the same issue, and having removed the min_freq arg.

Let me know if you need anything else! Thanks for the help! (I am not the OP so you might wait to close until he confirms fix too.)

**Closed** 2022-07-02 10:03 UTC
Labels: enhancement
